import Head from "next/head";
import { Inter } from "@next/font/google";
import style from "@/styles/connexion.module.css";




const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    if (process.browser) {
        test();
    }

    function test() {
    
    }


    
        



    return (
        <>
            <Head>
                <title>Connexion</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={style.main}>
                <div className={style.connexionBox}>
                <h1 className={style.title}>Connexion</h1>
                    <form className={style.connexionForm}>
                        <div className={style.connexionFormGroup}>
                            <input className={style.connexionFormInput} type="email" name="email" id="email" placeholder="Email"/>
                            <input className={style.connexionFormInput} type="password" name="password" id="password" placeholder="Mot de passe"/>
                            <button className={style.connexionFormButton} type="submit">Se connecter</button>
                            <input className={style.connexionFormCheckbox} type="checkbox" name="remember" id="remember"/>
                            <label className={style.connexionFormLabel} for="remember">Se souvenir de moi</label>
                        <p className={style.connexionFormText}>Vous n'avez pas de compte ? <a className={style.connexionFormLink} href="/creationdecompte">Inscrivez-vous</a></p>
                    </div>
                        </form>
                </div>
                
            </main>
        </>
    );
}
