import Head from "next/head";
import Image from "next/image";
import react from "react";
import { Inter } from "@next/font/google";
import style from "@/styles/cdc.module.css";




const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    if (process.browser) {
        test();
    }

    function test() {
        let page1 = document.getElementById("page1");
    let page2 = document.getElementById("page2");
    let page3 = document.getElementById("page3");
    let wrongPassword = document.getElementById("wrongPassword");
    let wrongPassword2 = document.getElementById("wrongPassword2");
    page2.style.display = "none";
    page3.style.display = "none";
    wrongPassword.style.display = "none";
    wrongPassword2.style.display = "none";

    }

    function commercant() {
        page1.style.display = "none";
        page2.style.display = "block";
    }
    function client() {
        page1.style.display = "none";
        page3.style.display = "block";
    }

    function Retour() {
        page1.style.display = "block";
        page2.style.display = "none";
        page3.style.display = "none";
    }

    function Submit() {
        wrongPassword.style.display = "none"
        /*Check the password was the same*/ 
        let password = document.getElementById("psw1").value;
        let password2 = document.getElementById("psw2").value;
        //check if all the fields are filled and if the password is the same
        if (password == null || password == "" || password2 == null || password2 == "") {
            console.log("Veuillez remplir tous les champs");
        }else if (password == password2){
            alert("Compte créé avec succès");
            window.location.href = "/connexion";
        }else if(password != password2){
            wrongPassword.style.display = "block";
            wrongPassword2.style.display = "block";
        }else{
            console.log("error");
        }

    }


 

    
        



    return (
        <>
            <Head>
                <title>CreationDeCompte</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={style.main}>
                <div className={style.box} id="page1">
                    <h1 className={style.text}>Creation De Compte</h1>
                    <div className={style.box2}>
                        <button type="button" className={style.button} onClick={commercant}>Commerçant</button>
                        <button type="button" className={style.button}onClick={client}>Client</button>
                    </div>
                    <p className={style.connexionFormText}>Vous avez déja un compte ? <a className={style.connexionFormLink} href="/connexion">Connexion</a></p>
                </div>
                <div className={style.box} id="page2">
                    <h1 className={style.text}>Commercant</h1>
                    <form onsubmit="return false">
                        <div className={style.Register}>
                        
                    <input type="text" placeholder="Nom D'utilisateur" className={style.inputs }required="required"/>
                    <input type="email" placeholder="Email" className={style.inputs} required="required"/>
                        <input type="password" placeholder="Password" id="psw1" className={style.inputs} required="required"/>
                        <input type="password" placeholder="Confirm Password" id="psw2" className={style.inputs} required="required"/>
                        <p className={style.checkPassword} id="wrongPassword">Wrong password</p> 
                        <button type="submit" className={style.button} onClick={Submit} >Suivant</button>
                        <button type="button" className={style.button} onClick={Retour}>Retour</button>
                    </div>
                    </form>
                </div>
                <div className={style.box} id="page3">
                    <h1 className={style.text}>Client</h1>
                    <form onsubmit="return false">
                        <div className={style.Register}>
                        
                    <input type="text" placeholder="Nom D'utilisateur" className={style.inputs }required="required"/>
                    <input type="email" placeholder="Email" className={style.inputs} required="required"/>
                        <input type="password" placeholder="Password" id="psw1" className={style.inputs} required="required"/>
                        <input type="password" placeholder="Confirm Password" id="psw2" className={style.inputs} required="required"/>
                        <p className={style.checkPassword} id="wrongPassword2">Wrong password</p>
                        <button type="submit" className={style.button} onClick={Submit} >Suivant</button>
                        <button type="button" className={style.button} onClick={Retour}>Retour</button>
                    </div>
                    </form>
                </div>
            </main>
        </>
    );
}
