import Head from "next/head";
import Image from "next/image";
import react from "react";
import { Inter } from "@next/font/google";
import style from "@/styles/cdc.module.css";




const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    if (process.browser) {
        test();
    }

    function test() {
        let page1 = document.getElementById("page1");
    let page2 = document.getElementById("page2");
    let page3 = document.getElementById("page3");
    page2.style.display = "none";
    page3.style.display = "none";
    }

    function commercant() {
        page1.style.display = "none";
        page2.style.display = "block";
    }
    function client() {
        page1.style.display = "none";
        page3.style.display = "block";
    }

    function Retour() {
        page1.style.display = "block";
        page2.style.display = "none";
        page3.style.display = "none";
    }

    
        



    return (
        <>
            <Head>
                <title>CreationDeCompte</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={style.main}>
                <div className={style.box} id="page1">
                    <h1 className={style.text}>Creation De Compte</h1>
                    <div className={style.box2}>
                        <button type="button" className={style.button} onClick={commercant}>Commerçant</button>
                        <button type="button" className={style.button}onClick={client}>Client</button>
                    </div>
                </div>
                <div className={style.box} id="page2">
                    <h1 className={style.text}>Commercant</h1>
                    <div className={style.Register}>
                    <input type="text" placeholder="Nom D'utilisateur" className={style.inputs}/>
                    <input type="text" placeholder="Email" className={style.inputs}/>
                        <input type="password" placeholder="Password" className={style.inputs}/>
                        <input type="password" placeholder="Confirm Password" className={style.inputs}/>
                        <button type="submit" className={style.button} >Suivant</button>
                        <button type="button" className={style.button} onClick={Retour}>Retour</button>
                    </div>
                </div>
                <div className={style.box} id="page3">
                    <h1 className={style.text}>Client</h1>
                    <div className={style.Register}>
                    <input type="text" placeholder="Nom D'utilisateur" className={style.inputs}/>
                        <input type="text" placeholder="Email" className={style.inputs}/>
                        <input type="password" placeholder="Password" className={style.inputs}/>
                        <input type="password" placeholder="Confirm Password" className={style.inputs}/>
                        <button type="submit" className={style.button} >Suivant</button>
                        <button type="button" className={style.button} onClick={Retour}>Retour</button>
                    </div>
                </div>
            </main>
        </>
    );
}
